version: '3'
services:
    pycontw-2012-2013:
        build: ./nginx
        container_name: pycontw-2012-2013
        hostname: pycontw-2012-2013
        volumes:
            - ./data:/var/www
        ports:
            - 8012:80
            - 8013:80

networks:
    default:
        external:
            name: pycontw-net
